/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CarbonIcon: typeof import('./src/components/icons/CarbonIcon.vue')['default']
    Chart: typeof import('./src/components/Chart/Chart.vue')['default']
    CopyRight: typeof import('./src/components/CopyRight/index.vue')['default']
    ElButton: typeof import('element-ui/lib/button')['default']
    ElCol: typeof import('element-ui/lib/col')['default']
    ElForm: typeof import('element-ui/lib/form')['default']
    ElFormItem: typeof import('element-ui/lib/form-item')['default']
    ElInput: typeof import('element-ui/lib/input')['default']
    ElRow: typeof import('element-ui/lib/row')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
    Table: typeof import('./src/components/Table/index.vue')['default']
  }
}
