/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CarbonIcon: typeof import('./src/components/icons/CarbonIcon.vue')['default']
    Chart: typeof import('./src/components/Chart/Chart.vue')['default']
    CopyRight: typeof import('./src/components/CopyRight/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
    Table: typeof import('./src/components/Table/index.vue')['default']
  }
}
