/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    Back: typeof import('./src/components/Back/index.vue')['default']
    Card: typeof import('./src/components/Card/index.vue')['default']
    CopyRight: typeof import('./src/components/CopyRight/index.vue')['default']
    DeleteModal: typeof import('./src/components/deleteModal.vue')['default']
    Dialog: typeof import('./src/components/Dialog/index.vue')['default']
    DynamicTooltip: typeof import('./src/components/DynamicTooltip.vue')['default']
    ErrPage: typeof import('./src/components/errPage.vue')['default']
    Form: typeof import('./src/components/Form/index.vue')['default']
    Page: typeof import('./src/components/Page/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search/index.vue')['default']
    SecretKey: typeof import('./src/components/secretKey.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/SvgIcon.vue')['default']
    Table: typeof import('./src/components/Table/index.vue')['default']
  }
}
