/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    Back: typeof import('./../components/Back/index.vue')['default']
    Card: typeof import('./../components/Card/index.vue')['default']
    Config: typeof import('./../common/js/config.ts')['default']
    CopyRight: typeof import('./../components/CopyRight/index.vue')['default']
    DeleteModal: typeof import('./../components/deleteModal.vue')['default']
    Dialog: typeof import('./../components/Dialog/index.vue')['default']
    DynamicTooltip: typeof import('./../components/DynamicTooltip.vue')['default']
    ErrPage: typeof import('./../components/errPage.vue')['default']
    Form: typeof import('./../components/Form/index.vue')['default']
    FormDefaultConfig: typeof import('./../components/Form/formDefaultConfig.ts')['default']
    ModalsDefaultConfig: typeof import('./../components/Dialog/modalsDefaultConfig.ts')['default']
    Page: typeof import('./../components/Page/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./../components/Search/index.vue')['default']
    SecretKey: typeof import('./../components/secretKey.vue')['default']
    SEllipsis: typeof import('./../components/S-Ellipsis/index.tsx')['default']
    SvgIcon: typeof import('./../components/SvgIcon/SvgIcon.vue')['default']
    Table: typeof import('./../components/Table/index.vue')['default']
    TableDefaultConfig: typeof import('./../components/Table/tableDefaultConfig.ts')['default']
  }
}
